---
title: "Ejemplos de gráficos programados por el ggplot2 y plotly"
format: html
toc: true
lang: es
theme: Simplex
---

# Carga de paquetes 

```{r}
#| label: Carga-paquetes
#| message: false
#| warning: false

library(tidyverse)
library(DT)
library(gapminder)
library(ggthemes)
library(hrbrthemes)
```

# Conjunto de datos

## mpg

```{r}
#| label: tabla-mpg

mpg |>
  select(manufacturer, year, cty, hwy) |>
  datatable(options = list(
      pageLength = 5,
      language = list
      (url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

## diamonds

```{r}
#| label: tabla-diamantes
#| message: false
#| warning: false

diamonds |>
  datatable(options = list(
      pageLength = 5,
      language = list
      (url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
  
```

##gapminder

```{r}
#| label: tabla-gapminder

gapminder |>
  datatable(options = list(
      pageLength = 5,
      language = list
      (url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
    )
  )
```

# ggplot2

```{r}
#| label: ggplot2-01

ggplot(data = mpg) + geom_point(aes(x = displ, y = hwy))
```

```{r}
#| label: ggplot2-02

mpg |>
  ggplot(aes(x = displ, y = hwy)) +
  geom_point()
```

```{r}
#| label: ggplot2-03

mpg |>
  ggplot(aes(x = displ, y = hwy, colour = class)) +
  geom_point()
```

```{r}
#| label: ggplot2-04
#| message: false
#| warning: false

mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, colour = class)) +
  geom_point()
```

```{r}
#| label: ggplot2-05

mpg |>
  ggplot(aes(x = displ, y = hwy, shape = class, colour = class)) +
  geom_point()+
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6)) +
  scale_color_manual(values = c("red", "blue", "green", "purple", "orange", "brown", "pink"))
```

```{r}
#| label: ggplot2-06

#Gráfico de dispersión que muestre la relación entre 
#el PIB per capita (x) y la esperanza de vida (y)

gapminder|>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```


```{r}
#| label: ggplot2-07

#Gráfico de dispersión que muestre la relación entre 
#el PIB per capita (x) y la esperanza de vida (y)
#para el año 2007

gapminder|>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point()
```

```{r}
#| label: ggplot2-08

#Gráfico de dispersión que muestre la relación entre 
#el PIB per capita (x) y la esperanza de vida (y)
#para el año 2007
#coloreado por continente

gapminder|>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, colour = continent)) +
  geom_point() 
```

```{r}
#| label: ggplot2-09
#| message: false
#| warning: false

#Gráfico de dispersión que muestre la relación entre 
#el PIB per capita (x) y la esperanza de vida (y)
#para el año 2007
#coloreado por continente

gapminder|>
  filter(year == 2007) |>
  ggplot(aes(x = gdpPercap, y = lifeExp, colour = continent)) +
  geom_point() + 
  geom_smooth(method = "lm") +
  ggtitle("Relación entre PIB per capita y esperza de vida en 2007") +
  xlab("PIB per capita EEUU ($)") +
  ylab("Esperanza de vida (años)") +
  labs(color = "Continente") +
  theme_solarized_2()
```

